### ISSUE TITLE
Stop after last word

### ISSUE THREAD

**Issue by pamzgs** [nateinaction/wp-morphext#1]
What do I need to add to the short code to make it stop after the last word?

**Comment by nateinaction** [comment]
Hey there! This plugin implements all features available in the Morphext library. It looks like stopping after a single loop through the word list is not a feature in Morphext. Morphext hasn't been updated in some time and may no longer be maintained but you could submit a feature request: https://github.com/MrSaints/Morphext/

**Comment by pamzgs** [comment]
Hi Nate, 

 

Thanks for getting back to me. I wrote you because it appears that Morphext did update his code to provide for this.

 

Here there is something about “Loops added” – wondered if this is the solution: https://github.com/MrSaints/Morphext/blob/f8f637ca006f910e801b469dccd737f7151a2838/dist/morphext.min.js 

 

Looking forward to your response!

Pam

**Comment by nateinaction** [comment]
Hey Pam, thanks again for reaching out! If Morphext does support stopping after the first loop I do not see it documented in the [README](https://github.com/MrSaints/Morphext/blob/master/README.md). It appears that there is an open feature request that a few people have posted in here: https://github.com/MrSaints/Morphext/issues/27

**Comment by pamzgs** [comment]
Ah- Ok – thanks it would be useful :) 

 

I am working on an alternative presentation that I can use the continuous loop with.

 

Thanks Nate!
