### ISSUE TITLE
version 1.3 is not working on wordpress 5

### ISSUE THREAD

**Issue by Anasxrt** [nateinaction/wp-morphext#2]
Hi,

the shortcode is not working any more. but it weird that I can use version 1.2

**Comment by nateinaction** [comment]
Hey @Anasxrt, Thanks for the report! I'll take a look at this today.

**Comment by nateinaction** [comment]
Thanks for giving 1.3 a try @Anasxrt! I see the issue. I'll work on getting it fixed up shortly.

**Comment by nateinaction** [comment]
This has been fixed and is available in the WP plugin repository as version `1.4.0`

**Comment by Anasxrt** [comment]
Hi @nateinaction 

I have updated it already, thanks for the great work!
