### ISSUE TITLE
How can I control the flipInX animation speed in the shortcode?

### ISSUE THREAD

**Issue by MarshCastle** [nateinaction/wp-morphext#3]
Nice plugin. Thanks for your work! :)

I'm trying to change the animation-duration in a shortcode, but can't see how to accomplish it (sorry - I'm probably missing something obvious). I can change the animation speed to control the time between animations, but not the speed of the animation itself.

I've tried the obvious (at least to me!):
```
[wpmorphext animation="flipInX" speed="3000" animation-duration="2000" text="Example 1, Example 2, etc"]
```
and variations (animation-duration="2s", duration="2s", duration="2000" etc),. but I don't seem to be able to affect the outcome.

I'm aware that I'm a newb to all of this, and easily overwhelmed, so please forgive my naivety when I ask: how do I control the animation speed to slow down the flipInX?

**Comment by nateinaction** [comment]
Hey @MarshCastle, Thanks for the ping. Sadly I have not used this plugin in quite some time and the tooling it's based on (Morphext) hasn't been updated in over a decade. It's probably best to not rely on this plugin. Best of luck in your text animating adventures!
